### ISSUE TITLE
文档没有说明redis的配置项

### ISSUE THREAD

**Issue by woeoio** [soybeanjs/soybean-admin-nestjs#10]
应该说明以下配置项, 否则启动后端会出错

![image](https://github.com/user-attachments/assets/100627c4-42b1-489c-8d52-eb088be3e1df)

**Comment by ByteByteBrew** [comment]
项目配置都在backend/libs/config/src/*.ts，如果按照本地docker快速启动应该不会有问题的，非docker环境下更改配置信息即可
