### ISSUE TITLE
是否有制作好的镜像推送到 hub 分享以下?

### ISSUE THREAD

**Issue by woeoio** [soybeanjs/soybean-admin-nestjs#8]
我这里打包出现好几个错误, 逐个排查了一下午, 还是有新问题, 梯子没问题, 谢谢

**Comment by ByteByteBrew** [comment]
> 我这里打包出现好几个错误, 逐个排查了一下午, 还是有新问题, 梯子没问题, 谢谢

请说明问题

**Comment by woeoio** [comment]
暂时先忙其他了, 谢谢
