### ISSUE TITLE
执行数据库初始化没有出错, 但是数据库没有创建表

### ISSUE THREAD

**Issue by woeoio** [soybeanjs/soybean-admin-nestjs#9]
执行数据库初始化没有出错, 但是数据库没有创建表

![image](https://github.com/user-attachments/assets/b33c14f2-a07e-4e74-a020-341a8d6c0b80)

**Comment by ByteByteBrew** [comment]
prisma:generate仅仅是生成prisma运行时所需元数据文件，生成数据表参照makefile或者prisma官方文档使用deploy或者push命令

**Comment by woeoio** [comment]
好
